# Application-wide configuration
server:
  port: 8080

spring:
  application:
    name: Eureka Server
eureka:
  client:
    # Don't register Eureka server in itself
    # It allows to start without exceptions
    register-with-eureka: false
    fetch-registry: false
  instance:
    # Name of current host, in this particular case it's better
    # to set it manually
    hostname: eureka
